### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfricaLabs/sensors.AFRICA-StormWatch#1]
The StormWatch app does the following:

1. Runs a script (hourly) to determine the probability of a storm.
2. Broadcasts SMS if storm predicted.

### Tasks:

- [ ] Create a Dokku deployable instance for running python script
- [ ] Create Python script that when run, acts like it's determining probability and returns randomly generated number between 1.0 and 0.0.
- [ ] Integrate RapidPro notification when probability threshold(s) met
- [ ] Create dokku app and setup cron-job on server
- [ ] Deploy test instance

### Files:

- RapidPro documentation ?
- Dokku documentation ?

### Notes:

We need to add in the `README.md` that this repo might be merged into https://github.com/CodeForAfricaLabs/VIEWS as part of turning the MatLab code into Python.

**Comment by chegejames** [comment]
@DavidLemayian https://github.com/CodeForAfricaLabs/sensors.AFRICA-StormWatch/pull/2
